### ISSUE TITLE
2FA does not load QR Code

### ISSUE THREAD

**Issue by andrucha97** [nuxsmin/sysPass#1690] opened 2021-04-14 10:38 UTC
**sysPass Version**
3.2 (322.21031301)
Config: 305.19020701
App: 310.19042701
DB: 310.19042701

Erweiterungen: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache

Authenticator
Version: 2.2.2
Autor: Rubén D.

**Describe the bug**

After Uprading to v 3.2 I cannot view the 2FA SVG Image

**To Reproduce**
1. Update to v 3.2 from 3.1
2. Click on '...'
3. Scroll down to 'User Settings'
4. Security
5. No Image of 2FA

**Expected behavior**

The QR Code is visible to scan with Phone

**Screenshots**
![image](https://user-images.githubusercontent.com/45176192/114696774-54f6b980-9d1d-11eb-931b-508e2fa0d39a.png)

**Event log**

```
[2021-04-14 12:34:32] syspass.ERROR: logger {"message":"Could not set locale","caller":"SP\Core\Language::setLocales"}
[2021-04-14 12:34:32] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2021-04-14 12:34:32] syspass.INFO: logger {"message":"Saved icons cache","caller":"SP\Core\UI\Theme::saveIcons"}
[2021-04-14 12:34:32] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2021-04-14 12:34:32] syspass.DEBUG: show.userSettings {"message":"N/A","user":"schulung","address":"********","caller":"SP\\Modules\\Web\\Controllers\\UserSettingsManagerController::getTabs"} []
[2021-04-14 12:34:32] syspass.DEBUG: show.userSettings {"message":"N/A","user":"schulung","address":"*******","caller":"SP\\Modules\\Web\\Controllers\\UserSettingsManagerController::getTabs"} []
[2021-04-14 12:34:36] syspass.ERROR: logger {"message":"Could not set locale","caller":"SP\Core\Language::setLocales"}
[2021-04-14 12:34:36] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2021-04-14 12:34:36] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2021-04-14 12:34:36] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}

```

**Platform (please complete the following information):**
 - OS: Linux
 - OS Version: Ubuntu 20.04
 - Browser: Chrome, Edge

**Additional context**

If I go back to Version 3.1 the extensions works. If I Update to 3.2 I need to reinstall the Plugin.

**Comment by grizzlydev-sarl** [comment] 2021-07-28 14:17
Same problem.
Duplicate of this : https://github.com/sysPass/plugin-Authenticator/issues/33
Perhaps related to the qrcode generator which seems to have problems depending on the locale: https://github.com/Bacon/BaconQrCode/issues/83

I solved it by commenting lines 192 through 199 in lib/SP/Core/Language.php:
```
//        $locale = setlocale(LC_ALL, $lang);

//        if ($locale === false) {
//            logger('Could not set locale to ' . $lang, 'ERROR');
//            logger('Domain path: ' . LOCALES_PATH);
//        } else {
//            logger('Locale set to: ' . $locale);
//        }
```

These lines are problematic anyway : https://github.com/nuxsmin/sysPass/issues/1494
They produce bucketloads of logs like these:
`[2021-07-28 16:04:07] syspass.ERROR: logger {"message":"Could not set locale to en_US.utf8","caller":"SP\Core\Language::setLocales"}`

**Comment by nuxsmin** [comment] 2021-09-18 09:45
Hello,

this feature was solved in latest Authenticator release.

Regards

**Closed by nuxsmin** 2021-09-18 09:45 UTC
