### ISSUE TITLE
Access to accounts as admin

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1148] opened 2018-11-29 16:12 UTC
**sysPass Version**
3.0-rc5 (also applicable to 2.1.16)

**Describe the question**
I have some accounts that seem "lost" in sysPass (both versions), meaning I know they exist, since I can search them with a `SELECT * FROM account WHERE name LIKE '%pattern%';`, but I can't access them.
User that created the account told me the group he used.
My user's primary group is that one, but I can't see the account.
Also, as admin, I don't see it neither.
I have added my user account to all groups, does not improve the situation.

Global search and Secondary group access are both enabled too.
Admin is also set as account admin, nothing helps.

Anything I may have missed ?
Maybe some diag steps I can do ?

Best regards.

**Comment by vmario89** [comment] 2018-11-29 16:23
Hi, admins dont see all created accounts if they are set to "private". In this case only the owner of the password is able to see it. I dont have another idea yet

**Comment by nuxsmin** [comment] 2018-11-29 16:31
@deajan it could be caused by what pointed @vmario89 , private accounts aren't visible by others than their owners or group (if private group is set). Please check out `isPrivate` and `isPriveteGroup` columns.

**Comment by vmario89** [comment] 2018-11-29 21:07
hi @deajan ,
this is a good question! You could do some update query for this to have some "dirty hack" which will work. 

But normally the sysPass-Admin(s) should think about some general usage concept for passwords and groups in the team/group/company. You should ask yourself some questions like "Who should save what kinds of passwords in a team password manager?". At first: I never would store private passwords which do not belong to the company for example (make your own instance for such a thing) - because an admin can build some API request to query that password (i think it should be possible, because in syspass v2 you can decrypt all passwords with XML decrypter) or to simply change the owner via database. 

A user in a company should only store passwords which belong to the company. Now these passwords/accounts can either belong to the private-only use of some personalized login (for example a vendor login like mario.voigt@somecompany.de at some third party) or some group-usage (like a team or squad or department which has shared access to something). This way the structure of groups and users should be applied accordingly. This will also lead that you normally should be able to delete the user's account without restoring his private-only passwords because you just won't require them. This also may be some data privacy break by the way if you recover some access of the user which does not belong to you. There's always the diversity between what should/should/must be done and what is not allowed in technical and philosophic way ;)

Hm just some ideas about it :-)

**Comment by nuxsmin** [comment] 2018-11-29 21:49
That's a good point @vmario89 

I'd use private accounts for VPN like resources, which are linked to the user and no one else should know them, other kind of usage in a corporate environment wouldn't have any sense (IMHO).

Transferring such accounts would be a non ethical action, since you'll give the ability to do any kind of impersonation when using to log in a service.

Regards

**Comment by deajan** [comment] 2018-11-29 23:58
@nuxsmin @vmario89 You both have some valid points.
My sysPass servers are for company passwords only that need to be shared among IT staff, and I have a separate solution for my own needs.
Here my problem was that a coworker added a remote office adsl line password as private, which I needed while he wasn't available. I ended up doing a dirty mysql hack in order to get the password and get the remote office back online.

From an ethical point of view, I understand this is a not to have feature.

Thanks.

**Comment by vmario89** [comment] 2018-11-30 00:05
Hi @deajan ,
you can prevent this by using the newer template engine to force group-only passwords :-)

**Comment by deajan** [comment] 2018-11-30 00:11
@vmario89 Sure... once we'll upgrade, that will be a nice setting :)
Guess you and I may have another week of fun testing all sorts of stuff in the RCs :)

**Comment by vmario89** [comment] 2018-11-30 10:14
Hey @deajan , i thought up many times if there are some methods/practices on doing the visual UI testing a little bit more concentrated and with some clear order. At the moment i am just clicking through and testing different stuff all the time :-D most times i find bugs and missing translations because sone feature down my eyes does not work the way i exspect haha :D I appreciate the development and community work for this project. Its nice to see that it evolves permanently

**Closed** 2019-02-23 12:09 UTC
Labels: kind/question, v3
