### ISSUE TITLE
Any group other than admins yields "La plantilla no contiene archivos"

### ISSUE THREAD

**Issue by dcotruta** [nuxsmin/sysPass#1063] opened 2018-10-10 15:52 UTC
**sysPass Version**
3.0-beta (300.18093001)

**Describe the bug**
When an (LDAP) user is added to anything other than the default Admins group, they cannot see any accounts (even within the primary group). All they get is the header and the text: "La plantilla no contiene archivos"

**To Reproduce**
1. Log in as LDAP user (may also apply to regular user accounts) to activate the account
2. See error message above.

**Expected behavior**
I would expect groups to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/1789225/46748600-d207ca80-ccab-11e8-80d3-eeed315e5b80.png)

**Event log**
[https://apaste.info/K0AG](https://apaste.info/K0AG) 
from the time of login to the template error seen at:
[2018-10-10 16:46:16 [EXCEPTION] [N/A] Template does not contain files]

**Platform (please complete the following information):**
UBUNTU 18.04
Apache/2.4.29 (Ubuntu)

Version: 7.2.10-1+ubuntu18.04.1+deb.sury.org+1 
SERVER_VERSION : 5.7.23-0ubuntu0.18.04.1 
CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

**Comment by odavis1** [comment] 2018-10-11 12:10
Hi, I am a colleague of dcotruta, I have pulled the latest version of syspass v3 (3.0-beta (300.18101101)) however this issue is still persistent with the same outcomes.

Additional testing:
I have created user group with a test member within, I have assigned this user group to a credential set as the main group. Log in with said test member and get header "La plantilla no contiene archivos"
I have created user group with a test member within, I have assigned this user group to a credential set as the Write group with the main being default Users group. Log in with said test member and get header "La plantilla no contiene archivos"

After login bottom left corner does show username, hovering over the user shows the User group they are part of.

**Comment by nuxsmin** [comment] 2018-10-12 08:06
Hi, this issue should be solved in latest commits though I couldn't trigger it on my test the environment, but the 'unknown offset' message would be caused by an array filtering which didn't reset the internal key index.

Thanks for the feedback and testing!

**Closed** 2018-10-28 22:34 UTC
Labels: BUG-Fixed, v3
