### ISSUE TITLE
Small bug with route for backup downloads

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1102] opened 2018-11-13 22:59 UTC
**sysPass Version**
3.0-rc1

Hi. I am running sysPass behind IPv4 NAT and forwarding it via Proxy to an offical web server with clean DNS/SSL etc.
Now i recognized that sysPass uses the internal URL (with https forwarding on port 8446) to download backup files but uses the proxy frontend URLs when browsing within sysPass. Due to those 2 different URLs i have to login a second time to the session from the internal URL. Is this a wanted feature? I blurred the screenshots but i hope you can see the differences

![grafik](https://user-images.githubusercontent.com/5631071/48448535-a8a4f780-e79f-11e8-8d2f-c5a2a0fd4b5e.png)
![grafik](https://user-images.githubusercontent.com/5631071/48448543-b490b980-e79f-11e8-800b-11e90ee2d72e.png)

regards, Mario

**Comment by nuxsmin** [comment] 2018-11-14 00:19
Hello, unfortunately this is not the intended behavior. It should point to browser's URL instead.

I'll fix it shortly. Thanks for the feedback!

Regards

**Comment by nuxsmin** [comment] 2018-11-17 17:53
Hey, this issue should be fixed in latest commit.

Regards

**Closed** 2018-11-25 12:07 UTC
Labels: BUG-Fixed, v3
