### ISSUE TITLE
Configure Login with Azure AD

### ISSUE THREAD

**Issue by sab1987** [nuxsmin/sysPass#1517] opened 2020-01-29 13:56 UTC
**sysPass Version**
3.1 (311.19121601)

**Describe the question**
Azure Active Directory Configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/60434031/73362226-3970d180-4285-11ea-88c1-a9f0420d8e2d.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 
 - OS Version: 18.04
 - Browser Any

**Additional context**
Good morning. Will they have any news regarding this problem?

Is there any other alternative that can be used with SysPass?

Many Thanks!

Regards,

**Comment by itpro-tips** [comment] 2020-01-29 16:40
Duplicate of #1415

**Comment by nuxsmin** [comment] 2020-02-02 11:24
Hello, this feature will be implemented in the minor release.

Regards

**Closed by nuxsmin** 2020-02-02 11:24 UTC
