### ISSUE TITLE
Copying a linked account requires password to be set

### ISSUE THREAD

**Issue by dvdfabian** [nuxsmin/sysPass#862] opened 2018-01-26 14:39 UTC
Hello,

there is a bug when copying an account with a linked password. If I create a new account and select the _linked account_ field I am unable to set up a password (which is a correct behavior). However, if I copy an existing linked account, the password field is required unless I de-select the linked account field and re-select it again. Then the password field gets disabled.

Best regards,

David Fabian

**Comment by vmario89** [comment] 2018-02-03 22:06
i recognized that copying an account copies all data but not the password from it. i think copying should be unserstood as a full duplicate of the account

**Comment by nuxsmin** [comment] 2019-04-27 10:39
3.1-RC1 has been released out, please check it out for solving this issue.

**Closed by nuxsmin** 2019-04-27 10:39 UTC
Labels: triage/need-fix, triage/ui
