### ISSUE TITLE
Ask for old password when change from passreset

### ISSUE THREAD

**Issue by uritau** [nuxsmin/sysPass#577] opened 2017-05-09 09:33 UTC
When a user use the feature "forgot password" receives the e-mail, can change the password, but when tries to log-in after that change, the system asks for the old password, I think as a measure of security.

It is possible to disable that security check? A user who use "forgot password" does not know the old password...

**Comment by nuxsmin** [comment] 2017-05-09 10:41
You're right, but it isn't a security check indeed...The old password is requested because when a password change is detected, you need to provide the master password (or a temporary one) to encrypt it using the new credentials, so to avoid to ask for the master pass, the app tries to get it from the previous user's password.

It's better explained here: https://doc.syspass.org/en/application/encryption.html#proceso-de-login

**Comment by Nadermane** [comment] 2017-05-12 14:35
This is really confusing for my end users. Is it possible to skip the "previous password" step and head straight to asking for the master password?

**Comment by nuxsmin** [comment] 2017-05-12 15:47
You're are right, it shouldn't ask for previous password when you're recovering it.

The last post was to clarify this behaviour, but I thought that it should be fixed.

**Comment by nuxsmin** [comment] 2017-07-31 11:17
Hello, this issue should have been solved in the latest commits.

Regards

**Closed by nuxsmin** 2017-07-31 11:17 UTC
Labels: Feature, NeedFix

**Comment by evangelina-compucorp** [comment] 2019-12-17 13:00
Hello @nuxsmin, we are experiencing this same issue with the last version 3.1. We were able to reproduce it several times, the password reset requests the old password first. The only workaround we found is to enter random characters there and in the next login it asks for the master password as it should. Do you know if this should be fixed on this version? Also, the users are having issues with their logins, if they dont login for a few days their passwords stop working and they need to be reset.
Thank you.
